# Generated by Django 5.1.1 on 2024-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_department_overview_delete_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.TextField(),
        ),
    ]
