# Generated by Django 5.1.1 on 2024-12-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_alter_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='image',
        ),
    ]
