# Generated by Django 5.1.1 on 2024-12-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_medicinebill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinebill',
            old_name='created_at',
            new_name='date_generated',
        ),
    ]
